services:
  app_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
      
  app:
    build: .
    environment:
      DB_CONNECTION_STRING: "Server=app_db;Database=AppDb;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:80"

    depends_on:
      - app_db

    ports:
      - "5000:80"

